<?php
declare(strict_types=1);

namespace Convermetry\Tests\Integration;

use mysqli;

/**
 * The subset of $wpdb the plugin's query layer uses, backed by a real MySQL
 * connection.
 *
 * This is NOT a mock. Every method here forwards to a live server, which is the
 * entire point: a hand-rolled mock would only prove the test author's model of
 * MySQL, and the bug this suite exists for — parameters binding to the wrong
 * placeholders — was invisible to exactly that kind of model.
 *
 * {@see prepare()} reimplements $wpdb's placeholder substitution rather than
 * using native prepared statements, deliberately. The plugin builds SQL by
 * string concatenation and hands it to $wpdb::prepare(), so reproducing that
 * substitution is what exercises the real code path — including the ordering of
 * bound parameters, which is precisely what went wrong.
 */
final class TestWpdb
{
    /** Table prefix, matching a default WordPress install. */
    public string $prefix = 'wp_';

    /**
     * Real $wpdb exposes the options table by name; the rate-limit counter
     * writes to it directly rather than through the options API.
     */
    public string $options = 'wp_options';

    /** The most recent error message, or '' — read by Analytics\ReportQuery. */
    public string $last_error = '';

    /** The id generated by the most recent INSERT. */
    public int $insert_id = 0;

    /** Rows affected by the most recent statement. */
    public int $rows_affected = 0;

    private mysqli $link;

    /**
     * @param mysqli $link A live connection.
     */
    public function __construct(mysqli $link)
    {
        $this->link = $link;
    }

    /**
     * Opens a connection from the environment, or returns null when none is
     * reachable so the suite can skip rather than fail.
     *
     * @return self|null
     */
    public static function fromEnvironment(): ?self
    {
        $socket = getenv('CVM_TEST_DB_SOCKET') ?: null;

        // mysqli only uses a socket when the host is 'localhost' — '127.0.0.1'
        // forces a TCP connection and the socket is silently ignored, which
        // presents as an unreachable server rather than a configuration error.
        $host = $socket !== null
            ? 'localhost'
            : (getenv('CVM_TEST_DB_HOST') ?: '127.0.0.1');

        $port = (int) (getenv('CVM_TEST_DB_PORT') ?: 3306);
        $name   = getenv('CVM_TEST_DB_NAME') ?: 'cvm_test';
        $user   = getenv('CVM_TEST_DB_USER') ?: 'root';
        $pass   = getenv('CVM_TEST_DB_PASS');
        $pass   = $pass === false ? '' : $pass;

        mysqli_report(MYSQLI_REPORT_OFF);

        try {
            $link = $socket !== null
                ? @new mysqli($host, $user, $pass, '', 0, $socket)
                : @new mysqli($host, $user, $pass, '', $port);
        } catch (\Throwable) {
            return null;
        }

        if ($link->connect_errno !== 0) {
            return null;
        }

        // Created rather than assumed: CI spins up an empty server, and a
        // developer should not have to prepare anything by hand.
        if (!$link->query('CREATE DATABASE IF NOT EXISTS `' . $link->real_escape_string($name) . '`')) {
            return null;
        }

        if (!$link->select_db($name)) {
            return null;
        }

        $link->set_charset('utf8mb4');

        return new self($link);
    }

    /**
     * Substitutes %s / %d placeholders the way $wpdb::prepare() does.
     *
     * @param string $sql  SQL containing placeholders.
     * @param mixed  ...$args Values, or a single array of values.
     * @return string
     */
    public function prepare(string $sql, ...$args): string
    {
        if (count($args) === 1 && is_array($args[0])) {
            $args = $args[0];
        }

        $out    = '';
        $index  = 0;
        $length = strlen($sql);

        for ($i = 0; $i < $length; $i++) {
            if ($sql[$i] !== '%' || $i + 1 >= $length) {
                $out .= $sql[$i];
                continue;
            }

            $next = $sql[$i + 1];

            if ($next === '%') {
                // An escaped literal percent.
                $out .= '%';
                $i++;
                continue;
            }

            if ($next !== 's' && $next !== 'd' && $next !== 'i' && $next !== 'f') {
                $out .= $sql[$i];
                continue;
            }

            $value = $args[$index] ?? '';
            $index++;
            $i++;

            $out .= match ($next) {
                'd'     => (string) (int) $value,
                'f'     => (string) (float) $value,
                'i'     => '`' . str_replace('`', '``', (string) $value) . '`',
                default => $value === null ? 'NULL' : "'" . $this->link->real_escape_string((string) $value) . "'",
            };
        }

        return $out;
    }

    /**
     * Runs a statement, returning affected rows or false on failure.
     *
     * @param string $sql Fully-prepared SQL.
     * @return int|false
     */
    public function query(string $sql): int|false
    {
        $this->last_error = '';

        $result = $this->link->query($sql);

        if ($result === false) {
            $this->last_error = $this->link->error;

            return false;
        }

        if ($result instanceof \mysqli_result) {
            $rows = $result->num_rows;
            $result->free();

            return $rows;
        }

        $this->insert_id     = (int) $this->link->insert_id;
        $this->rows_affected = (int) $this->link->affected_rows;

        return max(0, (int) $this->link->affected_rows);
    }

    /**
     * Runs a SELECT and returns every row.
     *
     * @param string $sql    Fully-prepared SQL.
     * @param string $output Ignored; ARRAY_A is always produced.
     * @return array<int, array<string, mixed>>
     */
    public function get_results(string $sql, string $output = ARRAY_A): array
    {
        $this->last_error = '';

        $result = $this->link->query($sql);

        if ($result === false) {
            $this->last_error = $this->link->error;

            return [];
        }

        $rows = $result instanceof \mysqli_result ? $result->fetch_all(MYSQLI_ASSOC) : [];

        if ($result instanceof \mysqli_result) {
            $result->free();
        }

        return $rows;
    }

    /**
     * Runs a SELECT and returns the first column of the first row.
     *
     * @param string $sql Fully-prepared SQL.
     * @return string|null
     */
    public function get_var(string $sql): ?string
    {
        $rows = $this->get_results($sql);

        if ($rows === []) {
            return null;
        }

        $first = reset($rows[0]);

        return $first === null ? null : (string) $first;
    }

    /**
     * Runs a SELECT and returns the first row.
     *
     * @param string $sql    Fully-prepared SQL.
     * @param string $output Ignored.
     * @return array<string, mixed>|null
     */
    public function get_row(string $sql, string $output = ARRAY_A): ?array
    {
        return $this->get_results($sql)[0] ?? null;
    }

    /**
     * Runs a SELECT and returns one column across every row.
     *
     * @param string $sql Fully-prepared SQL.
     * @return array<int, string>
     */
    public function get_col(string $sql): array
    {
        return array_map(
            static fn(array $row): string => (string) reset($row),
            $this->get_results($sql)
        );
    }

    /**
     * Updates rows, mirroring $wpdb::update()'s signature.
     *
     * @param string               $table   Table name.
     * @param array<string, mixed> $data    Column => value.
     * @param array<string, mixed> $where   Column => value.
     * @param array<int, string>   $format  Ignored; types come from the values.
     * @param array<int, string>   $wformat Ignored.
     * @return int|false
     */
    public function update(string $table, array $data, array $where, array $format = [], array $wformat = []): int|false
    {
        $set = [];
        foreach ($data as $column => $value) {
            $set[] = '`' . $column . '` = ' . $this->literal($value);
        }

        $conditions = [];
        foreach ($where as $column => $value) {
            $conditions[] = '`' . $column . '` = ' . $this->literal($value);
        }

        return $this->query(
            'UPDATE ' . $table . ' SET ' . implode(', ', $set)
            . ' WHERE ' . implode(' AND ', $conditions)
        );
    }

    /**
     * Deletes rows, mirroring $wpdb::delete()'s signature.
     *
     * @param string               $table  Table name.
     * @param array<string, mixed> $where  Column => value.
     * @param array<int, string>   $format Ignored.
     * @return int|false
     */
    public function delete(string $table, array $where, array $format = []): int|false
    {
        $conditions = [];
        foreach ($where as $column => $value) {
            $conditions[] = '`' . $column . '` = ' . $this->literal($value);
        }

        return $this->query('DELETE FROM ' . $table . ' WHERE ' . implode(' AND ', $conditions));
    }

    /**
     * Escapes a value for a LIKE pattern.
     *
     * @param string $text Raw text.
     * @return string
     */
    public function esc_like(string $text): string
    {
        return addcslashes($text, '_%\\');
    }

    /**
     * The charset/collate clause appended to every CREATE TABLE.
     *
     * @return string
     */
    public function get_charset_collate(): string
    {
        return 'DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci';
    }

    /**
     * The raw connection, for test setup that needs it directly.
     *
     * @return mysqli
     */
    public function link(): mysqli
    {
        return $this->link;
    }

    /**
     * Renders one value as a SQL literal, preserving NULL.
     *
     * @param mixed $value Value to render.
     * @return string
     */
    private function literal(mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        return "'" . $this->link->real_escape_string((string) $value) . "'";
    }
}
