<?php
declare(strict_types=1);

namespace Convermetry\Settings;

if (!defined('ABSPATH')) exit;

/**
 * One webhook endpoint as configured on the Webhooks page.
 *
 * Read out of the 'cvm_webhook_settings' option, which is why
 * {@see fromStoredArray()} coerces every field rather than trusting the
 * shape: the option is administrator-editable through the UI, through WP-CLI,
 * and through any filter a site has on option reads.
 *
 * $analytics and $forms are the two DELIVERY-TYPE flags, and they are
 * independent — an endpoint can receive scheduled reports, form submissions,
 * both, or (harmlessly) neither. They are the reason
 * {@see Options::analyticsEndpoints()} and {@see Options::formEndpoints()}
 * exist as separate lists.
 *
 * $secret is the endpoint's own signing secret. It is carried here because
 * the endpoint list is where it is configured, and it is deliberately NOT
 * exposed anywhere a delivery context, an Activity Log row, or a REST
 * response can reach — {@see Options::secretForId()} is the only reader.
 *
 * $id is the endpoint's DURABLE identity: an immutable, collision-resistant
 * value assigned once by {@see Options::ensureEndpointIds()} and never
 * regenerated by a routine save. Everything that outlives a single request —
 * the last-sent delivery window, retry state, retry cron arguments, and the
 * signing-secret lookup — is keyed by it. Those were all derived from
 * md5(url), so editing a URL reset the delivery window, orphaned the frozen
 * retry payload, and left a cron event wp_unschedule_event() could no longer
 * match: uncancellable, yet still firing.
 *
 * An endpoint read from storage before migration has an empty $id. Callers
 * must treat '' as "not yet migrated", never as a usable key.
 */
final readonly class WebhookEndpoint
{
    /**
     * @param string $url       Absolute endpoint URL, trimmed and non-empty.
     * @param string $label     Human-readable label, or ''.
     * @param string $secret    Per-endpoint signing secret, or '' to fall back to the shared one.
     * @param bool   $analytics Whether this endpoint receives scheduled analytics reports.
     * @param bool   $forms     Whether this endpoint receives form submissions.
     * @param string $id        Durable endpoint id, or '' when not yet migrated.
     */
    public function __construct(
        public string $url,
        public string $label = '',
        public string $secret = '',
        public bool $analytics = false,
        public bool $forms = false,
        public string $id = '',
    ) {
    }

    /**
     * Reads one stored endpoint row, or null when it carries no URL.
     *
     * A row without a URL is not an endpoint — it is a half-filled form the
     * administrator never completed — and has always been skipped rather than
     * stored as an empty destination.
     *
     * @param array<string, mixed> $entry A row from the endpoints option.
     * @return self|null
     */
    public static function fromStoredArray(array $entry): ?self
    {
        $url = trim((string) ($entry['url'] ?? ''));
        if ($url === '') {
            return null;
        }

        return new self(
            url: $url,
            label: trim((string) ($entry['label'] ?? '')),
            secret: trim((string) ($entry['secret'] ?? '')),
            analytics: !empty($entry['analytics']),
            forms: !empty($entry['forms']),
            id: trim((string) ($entry['id'] ?? '')),
        );
    }

    /**
     * The stored form, with the keys the option has always held.
     *
     * @return array{id: string, url: string, label: string, secret: string, analytics: bool, forms: bool}
     */
    public function toArray(): array
    {
        return [
            'id'        => $this->id,
            'url'       => $this->url,
            'label'     => $this->label,
            'secret'    => $this->secret,
            'analytics' => $this->analytics,
            'forms'     => $this->forms,
        ];
    }
}
